typography_spectrum: 0.27105089160613716
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.0524971978738904
  lightness: 0.47350313258357346
  saturation: 0.13801126275211573
  rhythmicContrast: 0.2790782917290926
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6091054670978338
analytics:
  google: null
  facebook: null
  twitter: null
name: Bomart
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
