name: Bomart
favicon: null
layout_spectrum: 0.4779145661741495
typography_spectrum: 0.8646696349605918
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000410'
    - '#a9b1d5'
    - '#637fa4'
    - '#d8d7df'
  brandStrength: 0.9656823608092964
  lightness: 0.8874076658394188
  saturation: 0.8280349941924214
  rhythmicContrast: 0.9026180843356997
purpose: []
