typography_spectrum: 0.06722738710232079
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.9381509348750114
  lightness: 0.6983600514940917
  saturation: 0.49054416292347014
  rhythmicContrast: 0.6202348105143756
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1901345974765718
analytics:
  google: null
  facebook: null
  twitter: null
name: Bomart
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Bomart Advies
description: Business Opportunity
purpose: []
