typography_spectrum: 0.8646696349605918
content_rating:
  adult: false
color:
  brandColors:
    - '#ffffff'
    - '#000410'
    - '#a9b1d5'
    - '#637fa4'
    - '#d8d7df'
  brandStrength: 0.9656823608092964
  lightness: 0.8874076658394188
  saturation: 0.8280349941924214
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4779145661741495
analytics:
  google: null
  facebook: null
  twitter: null
name: Bomart
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
